<a href="https://colab.research.google.com/github/handyhandoko/Belajar-Data-Science/blob/master/Basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pada tulisan kali, akan dibahas tentang operasi dasar menggunakan numpy.  Numpy adalah salah satu library yang digunakan untuk melakukan perhitungan menggunakan matriks/array.



**import numpy**

Untuk menggunakan, pertama-tama kita import dulu library numpy nya.

In [0]:
import numpy as np

**Array 1 dimensi**

Lalu kita akan coba membuat array 1 dimensi menggunakan numpy. Lalu kita coba lihat hasilnya dengan menggunakan perintah print.

In [15]:
array1D = np.array([2, 3, 4, 5, 6])
print (array1D)

[2 3 4 5 6]


Kalau array sudah muncul, itu berarti kita berhasil membuat array menggunakan numpy.

**Array 2 dimensi**

Sekarang kita coba membuat array 2 dimensi dengan menggunakan numpy.

In [7]:
array2D = np.array([ [2, 3, 4], [5, 6, 7] ])
print(array2D)

[[2 3 4]
 [5 6 7]]


**Indexing dan Slicing**

Array pada Numpy mirip array pada bahasa pemrograman lainnya dimana array memiliki index. Jadi mari kita coba indexing dan slicing array yang telah kita buat. Perlu diingat bahwa array dimulai dari 0.

Jadi, bukan cuman SPBU saja yang mulai dari 0. hehe...

In [10]:
print(array1D[1])

3


Indexing juga dapat kita gunakan untuk mengubah nilai dalam sebuah array.

In [20]:
print (array1D) #array sebelum diubah
print("")
array1D[0] = 0 #ubah array pada index 0 dengan nilai 5
print(array1D)

[7 3 4 5 6]

[0 3 4 5 6]


****

Sekarang kita coba untuk mengambil sebagian area dari array ini. Pada kali ini kita akan coba mengambil array ini dari index ke 2 hingga terakhir. Perlu diingat kembali, karena index dimulai dari 0, maka nilai akan diambil dari urutan ke 3 hingga terakhir.

In [18]:
print(array1D)
print("")
print(array1D[2:])

[5 3 4 5 6]

[4 5 6]


Kita juga bisa melakukan indexing pada array 2 dimensi.

In [22]:
print(array2D)
print("")
print(array2D[1, 1])

[[2 3 4]
 [5 6 7]]

6


Kita juga dapat mengambil sebagian dari array 2 dimensi. Kita coba untuk mengambil baris pertama dari array2D.

In [24]:
print(array2D)
print("")
print(array2D[0, :])

[[2 3 4]
 [5 6 7]]

[2 3 4]


Sekarang kita  coba untuk mengambil kolom kedua dari array 2D

In [25]:
print(array2D)
print("")
print(array2D[:, 1])

[[2 3 4]
 [5 6 7]]

[3 6]


**Operasi Matematika**

Sekarang kita coba lebih jauh, kita coba melakukan operasi matematika sederhana. Mari kita mulai coba dengan penjumlahan.

In [31]:
array1D_part1 = np.array([4, 2, 7])
array1D_part2 = np.array([1, 6, 3])

print(array1D_part1 + array1D_part2)



[ 5  8 10]


Selanjutnya kita coba dengan pengurangan.

In [34]:
print(array1D_part2 - array1D_part1)

[-3  4 -4]


Lalu kita coba dengan perkalian.

In [35]:
print(array1D_part2 * array1D_part1)

[ 4 12 21]


Operasi matematika tidak hanya berlaku untuk array 1 dimensi lho.

In [39]:
array2D_part1 = np.array([ [1, 5, 7], [2, 6, 0] ])
array2D_part2 = np.array([ [3, 6, 9], [2, 4, 8] ])

print(array2D_part1 + array2D_part2)
print("")
print(array2D_part2 - array2D_part1)
print("")
print(array2D_part1 * array2D_part2)

[[ 4 11 16]
 [ 4 10  8]]

[[ 2  1  2]
 [ 0 -2  8]]

[[ 3 30 63]
 [ 4 24  0]]
